log/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.sign_in_view),
    path('sign-in', views.sign_in_view),
    path('sign-up', views.sign_up_view),
    path('logout', views.logout_view),
    path('list', views.list_view),
    path('user-detail/<str:user_name>', views.user_detail_view),
    path('add-group/<str:user_name>', views.add_group_view),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
     path('', views.home_view),
     path('about', views.about_view),
     path('contact', views.contact_view),
     path('login', views.login_view),
     path('register', views.register_view),
     path('logout', views.logout_view),
     path('add-group', views.add_group_view),
     path('<slug:username>', views.account_view),
     path('<slug:group_id>/view', views.group_view),
     path('<slug:group_id>/add-expense', views.add_expense_view),
     path('<slug:group_id>/delete-group', views.delete_group_view),
     path('<slug:group_id>/settle/<slug:settler_id>', views.settle_view),
     path('<slug:group_id>/<int:expense_pk>/delete-expense', views.delete_expense_view),
     path('<slug:group_id>/<int:expense_pk>/edit-expense', views.edit_expense_view),
]

splitter/urls.py
from django.contrib import admin
from django.urls import path, include


from . import views


urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

log/models.py
# from django.conf import settings
from django.db import models
# from django.db.models import Q
# from django.utils import timezone


class LogUser(models.Model):  # blogpost_set -> queryset
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    user_name = models.SlugField(max_length=20)
    password = models.CharField(max_length=20)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.user_name

    def get_absolute_url(self):
        return f"/log/add-group/{self.user_name}"


class Group(models.Model):
    group_name = models.CharField(max_length=20)
    admin = models.ForeignKey(LogUser, on_delete=models.CASCADE)


class GroupUser(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    user = models.ForeignKey(LogUser, on_delete=models.CASCADE)

main/models.py
from django.db import models
from django.contrib.auth.models import User


class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(
        upload_to='main/static/img/profile_pictures', blank=True)

    def __str__(self):
        return self.user.get_username()

    def get_add_url(self):
        return f"/add-group"

    def get_absolute_url(self):
        return f"{self.user.get_username()}"

    def get_profile_picture_address(self):
        return self.profile_picture.url[4:]


class Group(models.Model):
    group_id = models.SlugField(max_length=20, unique=True)
    group_name = models.CharField(max_length=20)
    admin_fk = models.ForeignKey(Account, on_delete=models.CASCADE)
    group_picture = models.ImageField(
        upload_to='main/static/img/group_pictures', blank=True)

    def __str__(self):
        return self.group_id

    def get_absolute_url(self):
        return f"/{self.group_id}"

    def get_group_picture_address(self):
        return self.group_picture.url[4:]


class Expense(models.Model):
    expense_type = models.CharField(max_length=10, default='payment')
    group_fk = models.ForeignKey(Group, on_delete=models.CASCADE)
    adder_fk = models.ForeignKey(Account, on_delete=models.CASCADE,
                                 related_name='adder_fk')
    payer_fk = models.ForeignKey(Account, on_delete=models.CASCADE,
                                 related_name='payer_fk')
    title = models.CharField(max_length=20)
    cost = models.FloatField(default=0)
    date_time = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return self.title


class GroupMember(models.Model):
    group_fk = models.ForeignKey(Group, on_delete=models.CASCADE)
    member_fk = models.ForeignKey(Account, on_delete=models.CASCADE)
    balance = models.FloatField(default=0)

    def __str__(self):
        return f'{self.member_fk.user.get_username()} is in {self.group_fk.group_id}'


class ExpenseRatio(models.Model):
    expense_fk = models.ForeignKey(Expense, on_delete=models.CASCADE)
    member_fk = models.ForeignKey(Account, on_delete=models.CASCADE)
    ratio = models.FloatField(default=0)

    def __str__(self):
        s = f'"{self.member_fk.user.username}" used "{self.expense_fk.title}"'
        s += f' by ratio of "{self.ratio}"'
        s += f' in group {self.expense_fk.group_fk.group_id}'
        return s


class BalanceDetail(models.Model):
    group_fk = models.ForeignKey(Group, on_delete=models.CASCADE)
    debtor_fk = models.ForeignKey(
        Account, on_delete=models.CASCADE, related_name='debtor')
    creditor_fk = models.ForeignKey(
        Account, on_delete=models.CASCADE, related_name='creditor')
    amount = models.FloatField(default=0)

    def __str__(self):
        string = f'{self.debtor_fk.user.username} '
        string += f'owes {self.amount} '
        string += f'to {self.creditor_fk.user.username} '
        string += f'in {self.group_fk.group_id}'
        return string

main/forms.py
from django import forms
from .models import User, Group, Account


class ContactForm(forms.Form):
    full_name = forms.CharField()
    email = forms.EmailField()
    content = forms.CharField(widget=forms.Textarea)


class UserForm(forms.ModelForm):
    password = forms.CharField(max_length=20, widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['first_name', 'last_name',
                  'username', 'password']


class AccountForm(forms.ModelForm):
    class Meta():
        model = Account
        fields = ['profile_picture']


class GroupForm(forms.Form):
    group_id = forms.SlugField(max_length=20)
    group_name = forms.CharField(max_length=20)


class AddMemberForm(forms.Form):
    member_id = forms.SlugField(max_length=20)

main/views.py
from django.shortcuts import render, redirect

from .func import (settle, update_group_balances,
                   update_group_balance_details, update_expense_balances)

from .forms import (UserForm, AccountForm,
                    GroupForm, ContactForm, AddMemberForm)

from .models import (User, Account, Group, GroupMember, Expense,
                     ExpenseRatio, BalanceDetail)

from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required


def home_view(request):
    user = request.user
    try:
        account = Account.objects.get(user=user)
        return redirect(account_view, username=account.user.get_username())
    except Exception as exception:
        print(exception)
        context = {'title': 'Welcome to Splitter'}
        return render(request, 'home.html', context)


def about_view(request):
    context = {'title': 'About us'}
    return render(request, 'about.html', context)


def contact_view(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form = ContactForm()
    context = {"title": "Contact us", "form": form}
    return render(request, "form.html", context)


def register_view(request):
    user_form = UserForm(request.POST or None)
    account_form = AccountForm(request.POST or None, request.FILES or None)
    if user_form.is_valid() and account_form.is_valid():
        try:
            user = user_form.save()
            account = account_form.save(commit=False)
            account.user = user
            if 'profile_picture' in request.FILES:
                account.profile_picture = request.FILES['profile_picture']
            account.save()
            login(request, user)
            return redirect(account_view, username=user.get_username())
        except Exception as exception:
            print(exception)
    template_name = 'register.html'
    context = {'title': 'Register', 'user_form': user_form,
               'account_form': account_form}
    return render(request, template_name, context)


@login_required(login_url='/login')
def account_view(request, username):
    account = Account.objects.get(user=request.user)
    profile_account = Account.objects.get(
        user=User.objects.get(username=username))
    groups = GroupMember.objects.filter(member_fk=profile_account)
    if profile_account == account:
        template_name = 'account.html'
        title = 'Account Detail'
        context = {'title': title,
                   'account': account, 'groups': groups}
        return render(request, template_name, context)
    else:
        return redirect(home_view)


def login_view(request):
    title = None
    if request.method == 'POST':
        try:
            username = request.POST['username']
            password = request.POST['password']
            user = User.objects.get(username=username, password=password)
            login(request, user)
            return redirect(account_view, username=user.get_username())
        except Exception as exeption:
            print(exeption)
    else:
        title = "Login"
    context = {"title": title}
    template_name = 'login.html'
    return render(request, template_name, context)


@login_required(login_url='/login')
def logout_view(request):
    logout(request)
    return redirect(home_view)


@login_required(login_url='/login')
def add_group_view(request):
    account = Account.objects.get(user=request.user)
    try:
        group_id = request.POST['group_id']
        group_name = request.POST['group_name']
        group = Group.objects.create(group_id=group_id,
                                     group_name=group_name,
                                     admin_fk=account)
        GroupMember.objects.create(group_fk=group, member_fk=account)
    except Exception as exception:
        print(exception)
        title = 'Add New Group Error'
    return redirect(group_view, group_id=group_id)


@login_required(login_url='/login')
def edit_group_view(request, group_id):
    account = Account.objects.get(user=request.user)
    group = Group.objects.get(group_id=group_id)
    try:
        group_name = request.POST['group_name']
        group.group_name = group_name
        group.save()
    except Exception as exception:
        print(exception)
        title = 'Edit Group Error'
    return redirect(group_view, group_id=group_id)


@login_required(login_url='/login')
def delete_group_view(request, group_id):
    group = Group.objects.get(group_id=group_id)
    group.delete()
    return redirect(account_view, username=request.user.get_username())


@login_required(login_url='/login')
def settle_view(request, group_id, settler_id):
    account = Account.objects.get(user=request.user)
    group = Group.objects.get(group_id=group_id)
    settler = Account.objects.get(
        user=User.objects.get(username=settler_id))

    settle(account, group, settler)
    return redirect(group_view, group_id=group_id)


@login_required(login_url='/login')
def group_view(request, group_id):
    if request.method == 'POST':
        try:
            member_id = request.POST['member_id']
            group = Group.objects.get(group_id=group_id)
            member = Account.objects.get(
                user=User.objects.get(username=member_id))
            GroupMember.objects.create(group_fk=group, member_fk=member)

            expenses = Expense.objects.filter(group_fk=group)
            for expense in expenses:
                ExpenseRatio.objects.create(
                    expense_fk=expense, member_fk=member)
            return redirect(group_view, group_id=group_id)
        except Exception:
            title = 'Add New Member Error'
    else:
        title = 'Group'
    template_name = 'group.html'
    group = Group.objects.get(group_id=group_id)
    account = Account.objects.get(user=request.user)
    members = GroupMember.objects.filter(group_fk=group)
    expenses = Expense.objects.filter(group_fk=group)

    balance_details = BalanceDetail.objects.filter(group_fk=group)
    ratioes_list = []
    for expense in expenses:
        ratioes = ExpenseRatio.objects.filter(expense_fk=expense)
        ratioes_list.append(ratioes)
    details = {}
    for member in members:
        temp = {}
        for balance_detail in balance_details:
            if balance_detail.debtor_fk == member.member_fk:
                temp[balance_detail.creditor_fk.user.username] = balance_detail.amount
            elif balance_detail.creditor_fk == member.member_fk:
                temp[balance_detail.debtor_fk.user.username] = balance_detail.amount
        details[member.member_fk.user.username] = temp

    context = {'title': title, 'group': group,
               'members': members, 'account': account,
               'expenses': expenses, 'details': details,
               'ratioes_list': ratioes_list}
    return render(request, template_name, context)


@login_required(login_url='/login')
def add_expense_view(request, group_id):
    account = Account.objects.get(user=request.user)
    group = Group.objects.get(group_id=group_id)
    group_members = GroupMember.objects.filter(group_fk=group)
    members = []
    for member in group_members:
        members.append(member.member_fk)
    try:
        expense_type = 'payment'
        title = request.POST['title']
        payer_id = request.POST['payer_id']
        payer = Account.objects.get(
            user=User.objects.get(username=payer_id))
        cost = float(request.POST['cost'])
        expense = Expense(expense_type=expense_type, group_fk=group, adder_fk=account,
                          payer_fk=payer, title=title, cost=cost)
        expense.save()
        for member in members:
            ratio_of_username = f'ratio_of_{member.user.username}'
            ratio = float(request.POST[ratio_of_username])
            ExpenseRatio.objects.create(expense_fk=expense,
                                        member_fk=member,
                                        ratio=ratio)
        update_expense_balances(expense)
        update_group_balance_details(group)
    except Exception as exception:
        print(exception)
    return redirect(group_view, group_id=group_id)


@login_required(login_url='/login')
def delete_expense_view(request, group_id, expense_pk):
    expense = Expense.objects.get(pk=expense_pk)
    group = Group.objects.get(group_id=group_id)
    expense.delete()
    update_group_balances(group)
    update_group_balance_details(group)
    return redirect(group_view, group_id=group_id)


@login_required(login_url='/login')
def edit_expense_view(request, group_id, expense_pk):
    account = Account.objects.get(user=request.user)
    group = Group.objects.get(group_id=group_id)
    group_members = GroupMember.objects.filter(group_fk=group)
    expense = Expense.objects.get(pk=expense_pk)
    members = []
    for member in group_members:
        members.append(member.member_fk)
    try:
        expense.title = request.POST['title']
        payer_id = request.POST['payer_id']
        expense.payer_fk = Account.objects.get(
            user=User.objects.get(username=payer_id))

        expense.cost = float(request.POST['cost'])
        expense.save()
        for member in members:
            ratio_of_username = f'ratio_of_{member.user.username}'
            ratio = float(request.POST[ratio_of_username])
            expense_ratio = ExpenseRatio.objects.get(expense_fk=expense,
                                                     member_fk=member)
            expense_ratio.ratio = ratio
            expense_ratio.save()
        update_group_balances(group)
        update_group_balance_details(group)
    except Exception as exception:
        print(exception)
    return redirect(group_view, group_id=group_id)

main/templates/about.html
{% extends "base.html" %}


{% block head_title %}
{{ title }}
{% endblock %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

{% block content %}
<main role="main" class="container">
    <h1>Splitter</h1>
    <h5> By Ahmad & Assef</h5>
    <p>
        If you’re on a trip with friends or planning a picnic or party with co-workers, it is possible that someone will be paying the Uber bill while others are left paying for drinks or hotel costs. But you need to track all of these expenses and finally split the cost among the participants without ending up with mess.
        By using the Splitter, you can efficiently manage all costs per individual, track ‘who paid how much’ and ‘who should pay to whom’ via your mobile devices or from desktop browser.
        Just create a group and share it among the participants to add their expenses.
    </p>
</main>
{% endblock %}

main/templates/account.html
{% extends "base.html" %}

{% load static %}

{% block head_title %}
{% if title %}{{ title }}{% endif %}
{% endblock %}

{% block navbar %}
{% include 'breadcumber.html' %}
{% endblock %}

{% block content %}
<main role="main" class="container">
    <div class="jumbotron">
        <div class="row">
            {% for group in groups %}
            <div class="col col-12 col-sm-6 col-md-4 col-lg-3">
                <div class="card">
                    {% if group.group_picture %}
                    <img src="{{ group.get_group_picture_address }}" class="card-img-top" alt="img" width="100%">
                    {% else %}
                    <img src="{% static 'img/default-group-picture.png' %}" class="card-img-top" alt="img" width="100%">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ group.group_fk.group_name }}</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of
                            the
                            card's content.</p>
                        <a href="{{ group.group_fk.get_absolute_url }}/view" class="btn btn-outline-primary">View this
                            group</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</main>
{% endblock %}

main/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}" />
    {% block style %}{% endblock %}
    <title>Splitter {% block head_title %}{% endblock %}</title>
</head>

<body>
    <header>
        {% block navbar %}{% endblock %}
    </header>
    
    {% block content %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block js %}{% endblock %}
</body>

</html>

main/templates/breadcumber.html
{% load static %}

<div class="dropdown" style="position: absolute; right: 7%; padding-top: 3px;">
    {% if account.profile_picture %}
    <img src="{{ account.get_profile_picture_address }}" class="rounded-circle" width="40" height="40"></img>
    {% else %}
    <img src="{% static 'img/default-profile-picture.png' %}" class="rounded-circle" width="40" height="40"></img>
    {% endif %}
    <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false">
        {{account.user.get_short_name}}
    </button>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="/">Profile</a>
        <a class="dropdown-item" href="/logout">Logout</a>
        <button class="dropdown-item" data-toggle="modal" data-target="#createGroup">Create group</button>
    </div>
    <div class="modal fade" id="createGroup" tabindex="-1" role="dialog" aria-labelledby="createGroupTitle"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-scrollable" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="createGroupTitle">Create Group</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method='POST' action="{{ account.get_add_url }}"> {% csrf_token %}
                        <div class="form-group row">
                            <label for="id_group_name" class="col-sm-3 col-form-label">Group Name</label>
                            <div class="col-sm-9">
                                <input name="group_name" type="text" id="id_group_name" class="form-control"
                                    placeholder="Group Name" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="id_group_id" class="col-sm-3 col-form-label">Group id</label>
                            <div class="col-sm-9">
                                <input name="group_id" type="text" id="id_group_id" class="form-control"
                                    placeholder="Group id" required autofocus>
                            </div>
                        </div>
                        <div class="row justify-content-center">
                            <button type="submit" class="col col-10 col-md-6 btn btn-primary"
                                style="width: 100%;">Create</button>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

                </div>
            </div>
        </div>
    </div>
</div>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        {% if group %}
        <li class="breadcrumb-item"><a href="/{{account.get_absolute_url}}">{{account.user.get_short_name}}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{group.group_name}}</li>
        {% else %}
        <li class="breadcrumb-item active" aria-current="page">{{account.user.get_short_name}}</li>
        {% endif %}
    </ol>
</nav>

main/templates/form.html
{% extends "base.html" %}

{% block head_title %}
{% if title %}{{ title }}{% endif %}
{% endblock %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

{% block content %}
<form method='POST' action='.' enctype='multipart/form-data'> {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Send</button>
</form>
{% endblock %}

main/templates/list.html
{% extends "base.html" %}


{% block content %}

<div class='row'>
    {% for account in accounts %}
    <div class='col-12 col-md-10 mb-3 mx-auto'>
        <div class='card'>
            <div class='card-body'>
                <h5 class='card-title'>{{ account.account_id }}</h5>
                <p class='card-text'>
                    <small class='text-muted'>{{ account.first_name }}</small>
                </p>
            </div>

        </div>
    </div>
    {% endfor %}
</div>


{% endblock %}

main/templates/login.html
{% extends "base.html" %}
{% load static %}

{% block style %}
<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }
</style>
<link rel="stylesheet" type="text/css" href="{% static 'css/signin.css' %}">
{% endblock %}

{% block head_title %}
{% if title %}{{ title }}{% endif %}
{% endblock %}

{% block content %}
<main role="main" class="container">
<div class="text-center">
    <a href="/">
        <img class="mb-4" src="{% static 'img/favicon.png' %}" alt="LOGO" width="72" height="72">
    </a>
    <h1 class="h3 mb-3 font-weight-normal">Please Login</h1>
    <form class="form-signin" method="POST" action="/login"> {% csrf_token %}
        <label for="username" class="sr-only">Username</label>
        <input name="username" type="text" class="form-control" placeholder="Username" required autofocus>
        <label for="password" class="sr-only">Password</label>
        <input name="password" type="password" class="form-control" placeholder="Password" required>
        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2019</p>
    </form>
</div>
</main>
{% endblock %}

main/templates/logout.html
{% extends "base.html" %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

{% block content %}
<main role="main" class="container">
    <div class="row">
        <div class="col-md-3 col-12">
            <form method='POST' action="{{ account.get_add_url }}"> {% csrf_token %}
                <p>
                    Are you sure you want to logout?
                </p>
                <button type="submit" name="yes_sub" class="btn btn-primary">Yes</button>
                <button type="submit" name="no_sub" class="btn btn-primary">No</button>
            </form>
        </div>
    </div>
</main>
{% endblock %}

main/templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Splitter</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/login">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/register">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/contact">Contact us</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/about">About</a>
            </li>
        </ul>
    </div>
</nav>

main/templates/sign-up.html
{% extends "base.html" %}

{% block style %}
{% load static %}
<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }
</style>
<link rel="stylesheet" type="text/css" href="{% static 'css/signin.css' %}">
{% endblock %}

{% block head_title %}
{% if title %}{{ title }}{% endif %}
{% endblock %}

{% block content %}
<div class="text-center">
    <img class="mb-4" src="{% static 'img/bootstrap-solid.svg' %}" alt="LOGO" width="72" height="72">
    <h1 class="h3 mb-3 font-weight-normal">Please sign up</h1>
    <form class="form-signin" method="POST" action="/sign-up"> {% csrf_token %}
        <label for="id_first_name" class="sr-only">First Name</label>
        <input name="first_name" type="text" id="id_first_name" class="form-control" placeholder="First Name" required
            autofocus>
            <label for="id_last_name" class="sr-only">Last Name</label>
            <input name="last_name" type="text" id="id_last_name" class="form-control" placeholder="Last Name" required>
            <label for="id_account_id" class="sr-only">Username</label>
            <input name="account_id" type="text" id="id_account_id" class="form-control" placeholder="Username" required>
            <label for="id_password" class="sr-only">Password</label>
            <input name="password" type="password" id="id_password" class="form-control" placeholder="Password" aria-describedby="help" required>
            <small id="help" class="form-text text-muted">We'll never share your data with anyone else.</small>
        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2019</p>
    </form>
</div>
{% endblock %}

main/templates/user-detail.html
{% extends "base.html" %}


{% block content %}
<div class='col-12 col-md-10 mb-3 mx-auto'>
    <div class='card'>
        <div class='card-body'>
            <p class='card-title'>{{ user.first_name }}</p>
            <p class='card-title'>{{ user.last_name }}</p>
            <p class='card-text'>{{ user.user_name }}</p>
            <p class='card-text'>{{ user.description }}</p>
        </div>
    </div>
</div>

<ul class="list-group">
    {% for group in groups %}
    <a href="">
        <li class="list-group-item">{{ group }}</li>
    </a>
    {% endfor %}
</ul>
<a class="btn btn-primary" href="{{ user.get_absolute_url }}" role="button">Add Group</a>
{% endblock %}